export const Product = [
    {
        id : 1,
        Name : 'Sufyan',
        Price : 100,
        Brand : 'Acer',
        Image : 'https://images.pexels.com/photos/5212324/pexels-photo-5212324.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260',
        Category : "Men",
        Color : 'Red',
        Size : 'M',
        Department : 'Cloths',
        Action : 'Edit | Delete',
    },{
        id : 2,
        Name : 'Sufyan',
        Price : 100,
        Brand : 'Acer',
        Image : 'https://images.pexels.com/photos/5212324/pexels-photo-5212324.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260',
        Category : "Men",
        Color : 'Red',
        Size : 'M',
        Department : 'Cloths',
        Action : 'Edit | Delete',
    },{
        id : 3,
        Name : 'Sufyan',
        Price : 100,
        Brand : 'Acer',
        Image : 'https://images.pexels.com/photos/5212324/pexels-photo-5212324.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260',
        Category : "Men",
        Color : 'Red',
        Size : 'M',
        Department : 'Cloths',
        Action : 'Edit | Delete',
    },{
        id : 4,
        Name : 'Sufyan',
        Price : 100,
        Brand : 'Acer',
        Image : 'https://images.pexels.com/photos/5212324/pexels-photo-5212324.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260',
        Category : "Men",
        Color : 'Red',
        Size : 'M',
        Department : 'Cloths',
        Action : 'Edit | Delete',
    }
]